/**
 * Usage : Put this script in <ScriptsDir>/project_changed folder. Create a folder if it doesn't exists.
 *
 * @authors 	Yu Tang, Manuel Souto Pico
 * @version 	0.5.2 (dynamic)
 * @date 		2020.11.24
 */

import static org.omegat.core.events.IProjectEventListener.PROJECT_CHANGE_TYPE.*


// prepare
String dir
def replacePair

def skipTraverse(eventType) {
    if (!eventType.metaClass.hasProperty(eventType, 'skipTraverse')) {
        eventType.metaClass.skipTraverse = false
    }
    eventType.skipTraverse
}

switch (eventType) {
    case LOAD:
        // Skip traverse
        if (skipTraverse(LOAD)) {
			LOAD.skipTraverse = false // reset the flag
			return
        }

        dir = project.projectProperties.sourceRoot
        replacePair = [
			// locks tu's corresponding to titles (OVERDOING: it hides S1, etc.)
			//// [find: /(?<=<trans-unit\s)[^>]*?(?=>[\s\n]+<source.+?>(?:[CQSPMRF]{1,2}\d+(?:.+?)?|.+?Q\d+)<\/source>)/, replacement: {it.contains('translate')? it : /$it translate="no"/}],
			// locks tu's corresponding to titles (OK, only unit titles)
	  			// [find: /(?<=<trans-unit\s)[^>]*?(?=>[\s\n]+<source.+?>(?:[CQSPMRF]{1,2}\d{2}(\d|[KG]).+?(Q\d+)?)<\/source>)/, replacement: {it.contains('translate')? it : /$it translate="no"/}],
	  		// removes the source segment in the alternative translation
			[find: /<alt-trans[^>]*>\n\s*<source.+?>.+?\/source>/, replacement: /<alt-trans>/],
			// removes doctype declaration
			[find: /\n<!DOCTYPE xliff [^>]+ "http[^>]+xliff.dtd">/, replacement: / /],
			// switches the approved status from no to yes, otherwise translation might not show with Okapi XLIFF filter (if it's identical to source)
			[find: /approved="no"/, replacement: /approved="yes"/],
			// adds attribute-value pair approved=yes, otherwise translation does not show with Okapi XLIFF filter (if it's identical to source)
			[find: /(?<=<trans-unit\s)[^>]*?(?=>)/, replacement: {it.contains('approved')? it : /$it approved="yes"/}],
			// sets xml:space to preserve to avoid leading and trailing spaces being removed in exported files
			[find: /xml:space="(?!preserve)[^"]+"/, replacement: /xml:space="preserve"/],
			// adds the xml:space = preserve if it's not there
			[find: /(?<=<file\s)[^>]*?(?=>)/, replacement: {it.contains('xml:space')? it : /$it xml:space="preserve"/}],
			// converts ETS language codes to OmegaT language codes
			[find: /"afr-ZAF"/, replacement: /"af-ZA"/],
			[find: /"aka-GHA"/, replacement: /"ak-GH"/],
			[find: /"amh-ETH"/, replacement: /"am-ET"/],
			[find: /"amh-ZZZ"/, replacement: /"am-ZZ"/],
			[find: /"ara-ARE"/, replacement: /"ar-AE"/],
			[find: /"ara-BHR"/, replacement: /"ar-BH"/],
			[find: /"ara-DJI"/, replacement: /"ar-DJ"/],
			[find: /"ara-DZA"/, replacement: /"ar-DZ"/],
			[find: /"ara-EGY"/, replacement: /"ar-EG"/],
			[find: /"ara-IRQ"/, replacement: /"ar-IQ"/],
			[find: /"ara-ISR"/, replacement: /"ar-IL"/],
			[find: /"ara-JOR"/, replacement: /"ar-JO"/],
			[find: /"ara-KWT"/, replacement: /"ar-KW"/],
			[find: /"ara-LBY"/, replacement: /"ar-LY"/],
			[find: /"ara-MAR"/, replacement: /"ar-MA"/],
			[find: /"ara-OMN"/, replacement: /"ar-OM"/],
			[find: /"ara-PSE"/, replacement: /"ar-PS"/],
			[find: /"ara-QAT"/, replacement: /"ar-QA"/],
			[find: /"ara-SAU"/, replacement: /"ar-SA"/],
			[find: /"ara-SYR"/, replacement: /"ar-SY"/],
			[find: /"ara-TUN"/, replacement: /"ar-TN"/],
			[find: /"ara-UAE"/, replacement: /"ar-DU"/],
			[find: /"ara-YEM"/, replacement: /"ar-YE"/],
			[find: /"ara-ZZZ"/, replacement: /"ar-ZZ"/],
			[find: /"aze-QAZ"/, replacement: /"az-QZ"/],
			[find: /"azj-GEO"/, replacement: /"az-GE"/],
			[find: /"bam-MLI"/, replacement: /"bm-ML"/],
			[find: /"bel-BLR"/, replacement: /"be-BY"/],
			[find: /"bel-ZZZ"/, replacement: /"be-ZZ"/],
			[find: /"ben-BGD"/, replacement: /"bn-BD"/],
			[find: /"ben-IND"/, replacement: /"bn-IN"/],
			[find: /"bik-PHL"/, replacement: /"bik-PH"/],
			[find: /"bos-BIH"/, replacement: /"bs-BA"/],
			[find: /"bos-SRB"/, replacement: /"bs-RS"/],
			[find: /"bul-BGR"/, replacement: /"bg-BG"/],
			[find: /"cab-HND"/, replacement: /"cab-HN"/],
			[find: /"cat-ESP"/, replacement: /"ca-ES"/],
			[find: /"ceb-PHL"/, replacement: /"ceb-PH"/],
			[find: /"ces-CZE"/, replacement: /"cs-CZ"/],
			[find: /"cym-QUK"/, replacement: /"cy-GB"/],
			[find: /"dag-GHA"/, replacement: /"dag-GH"/],
			[find: /"dan-DNK"/, replacement: /"da-DK"/],
			[find: /"deu-AUT"/, replacement: /"de-AT"/],
			[find: /"deu-BEL"/, replacement: /"de-BE"/],
			[find: /"deu-CHE"/, replacement: /"de-CH"/],
			[find: /"deu-DEU"/, replacement: /"de-DE"/],
			[find: /"deu-ITA"/, replacement: /"de-IT"/],
			[find: /"deu-LIE"/, replacement: /"de-LI"/],
			[find: /"deu-LUX"/, replacement: /"de-LU"/],
			[find: /"deu-ZZZ"/, replacement: /"de-ZZ"/],
			[find: /"dje-NER"/, replacement: /"dje-NE"/],
			[find: /"dyu-BFA"/, replacement: /"dyu-BF"/],
			[find: /"dzo-BTN"/, replacement: /"dz-BT"/],
			[find: /"ell-ALB"/, replacement: /"el-AL"/],
			[find: /"ell-GRC"/, replacement: /"el-GR"/],
			[find: /"ell-QCY"/, replacement: /"el-CY"/],
			[find: /"eng-ARE"/, replacement: /"en-AE"/],
			[find: /"eng-AUS"/, replacement: /"en-AU"/],
			[find: /"eng-AUT"/, replacement: /"en-AT"/],
			[find: /"eng-BHR"/, replacement: /"en-BH"/],
			[find: /"eng-BRN"/, replacement: /"en-BN"/],
			[find: /"eng-BTN"/, replacement: /"en-BT"/],
			[find: /"eng-BWA"/, replacement: /"en-BW"/],
			[find: /"eng-CAN"/, replacement: /"en-CA"/],
			[find: /"eng-EGY"/, replacement: /"en-EG"/],
			[find: /"eng-ENG"/, replacement: /"en-EN"/],
			[find: /"eng-ESP"/, replacement: /"en-ES"/],
			[find: /"eng-GBR"/, replacement: /"en-GB"/],
			[find: /"eng-GHA"/, replacement: /"en-GH"/],
			[find: /"eng-HKG"/, replacement: /"en-HK"/],
			[find: /"eng-IRL"/, replacement: /"en-IE"/],
			[find: /"eng-JAM"/, replacement: /"en-JM"/],
			[find: /"eng-KEN"/, replacement: /"en-KE"/],
			[find: /"eng-KWT"/, replacement: /"en-KW"/],
			[find: /"eng-LBN"/, replacement: /"en-LB"/],
			[find: /"eng-LUX"/, replacement: /"en-LU"/],
			[find: /"eng-MAC"/, replacement: /"en-MO"/],
			[find: /"eng-MLT"/, replacement: /"en-MT"/],
			[find: /"eng-MUS"/, replacement: /"en-MU"/],
			[find: /"eng-MYS"/, replacement: /"en-MY"/],
			[find: /"eng-NGA"/, replacement: /"en-NG"/],
			[find: /"eng-NIR"/, replacement: /"en-BU"/],
			[find: /"eng-NOR"/, replacement: /"en-NO"/],
			[find: /"eng-NZL"/, replacement: /"en-NZ"/],
			[find: /"eng-OMN"/, replacement: /"en-OM"/],
			[find: /"eng-PAN"/, replacement: /"en-PA"/],
			[find: /"eng-PHL"/, replacement: /"en-PH"/],
			[find: /"eng-QAT"/, replacement: /"en-QA"/],
			[find: /"eng-QCY"/, replacement: /"en-CY"/],
			[find: /"eng-QIN"/, replacement: /"en-IN"/],
			[find: /"eng-QSC"/, replacement: /"en-AB"/],
			[find: /"eng-QUK"/, replacement: /"en-SU"/],
			[find: /"eng-SAU"/, replacement: /"en-SA"/],
			[find: /"eng-SGP"/, replacement: /"en-SG"/],
			[find: /"eng-SWE"/, replacement: /"en-SE"/],
			[find: /"eng-TAP"/, replacement: /"en-TW"/],
			[find: /"eng-TTO"/, replacement: /"en-TT"/],
			[find: /"eng-USA"/, replacement: /"en-US"/],
			[find: /"eng-ZAF"/, replacement: /"en-ZA"/],
			[find: /"eng-ZZZ"/, replacement: /"en-ZZ"/],
			[find: /"esp-ARG"/, replacement: /"es-AR"/],
			[find: /"esp-BOL"/, replacement: /"es-BO"/],
			[find: /"esp-CHL"/, replacement: /"es-CL"/],
			[find: /"esp-COL"/, replacement: /"es-CO"/],
			[find: /"esp-CRI"/, replacement: /"es-CR"/],
			[find: /"esp-DOM"/, replacement: /"es-DO"/],
			[find: /"esp-ECU"/, replacement: /"es-EC"/],
			[find: /"esp-ESP"/, replacement: /"es-ES"/],
			[find: /"esp-GTM"/, replacement: /"es-GT"/],
			[find: /"esp-HND"/, replacement: /"es-HN"/],
			[find: /"esp-MEX"/, replacement: /"es-MX"/],
			[find: /"esp-NIC"/, replacement: /"es-NI"/],
			[find: /"esp-PAN"/, replacement: /"es-PA"/],
			[find: /"esp-PER"/, replacement: /"es-PE"/],
			[find: /"esp-PRI"/, replacement: /"es-PR"/],
			[find: /"esp-PRY"/, replacement: /"es-PY"/],
			[find: /"esp-SLV"/, replacement: /"es-SV"/],
			[find: /"esp-URY"/, replacement: /"es-UY"/],
			[find: /"esp-USA"/, replacement: /"es-US"/],
			[find: /"esp-VEN"/, replacement: /"es-VE"/],
			[find: /"esp-ZZZ"/, replacement: /"es-ZZ"/],
			[find: /"est-EST"/, replacement: /"et-EE"/],
			[find: /"eus-ESP"/, replacement: /"eu-ES"/],
			[find: /"ewe-GHA"/, replacement: /"ee-GH"/],
			[find: /"fao-DNK"/, replacement: /"fo-DK"/],
			[find: /"fas-AFG"/, replacement: /"fa-AF"/],
			[find: /"fas-IRN"/, replacement: /"fa-IR"/],
			[find: /"fas-ZZZ"/, replacement: /"fa-ZZ"/],
			[find: /"fin-FIN"/, replacement: /"fi-FI"/],
			[find: /"fra-BEL"/, replacement: /"fr-BE"/],
			[find: /"fra-BFA"/, replacement: /"fr-BF"/],
			[find: /"fra-CAN"/, replacement: /"fr-CA"/],
			[find: /"fra-CHE"/, replacement: /"fr-CH"/],
			[find: /"fra-COD"/, replacement: /"fr-CD"/],
			[find: /"fra-FRA"/, replacement: /"fr-FR"/],
			[find: /"fra-LBN"/, replacement: /"fr-LB"/],
			[find: /"fra-LUX"/, replacement: /"fr-LU"/],
			[find: /"fra-MAR"/, replacement: /"fr-MA"/],
			[find: /"fra-NER"/, replacement: /"fr-NE"/],
			[find: /"fra-SEN"/, replacement: /"fr-SN"/],
			[find: /"fra-ZZZ"/, replacement: /"fr-ZZ"/],
			[find: /"ful-BFA"/, replacement: /"fuh-BF"/],
			[find: /"ful-NER"/, replacement: /"fuq-NE"/],
			[find: /"gaa-GHA"/, replacement: /"gaa-GH"/],
			[find: /"geo-GEO"/, replacement: /"ka-GE"/],
			[find: /"gle-IRL"/, replacement: /"ga-IE"/],
			[find: /"glg-ESP"/, replacement: /"gl-ES"/],
			[find: /"grn-PRY"/, replacement: /"gn-PY"/],
			[find: /"guj-IND"/, replacement: /"gu-IN"/],
			[find: /"hat-HAT"/, replacement: /"ht-HT"/],
			[find: /"hau-GHA"/, replacement: /"ha-GH"/],
			[find: /"hau-NER"/, replacement: /"ha-NE"/],
			[find: /"hau-NGA"/, replacement: /"ha-NG"/],
			[find: /"heb-ISR"/, replacement: /"he-IL"/],
			[find: /"hil-PHL"/, replacement: /"hil-PH"/],
			[find: /"hin-QIN"/, replacement: /"hi-IN"/],
			[find: /"hrv-BIH"/, replacement: /"hr-BA"/],
			[find: /"hrv-HRV"/, replacement: /"hr-HR"/],
			[find: /"hun-HUN"/, replacement: /"hu-HU"/],
			[find: /"hun-ROU"/, replacement: /"hu-RO"/],
			[find: /"hun-SRB"/, replacement: /"hu-RS"/],
			[find: /"hun-SVK"/, replacement: /"hu-SK"/],
			[find: /"hun-SVN"/, replacement: /"hu-SI"/],
			[find: /"hye-ARM"/, replacement: /"hy-AM"/],
			[find: /"ibo-NGA"/, replacement: /"ig-NG"/],
			[find: /"ind-IDN"/, replacement: /"id-ID"/],
			[find: /"ind-TLS"/, replacement: /"id-TL"/],
			[find: /"isl-ISL"/, replacement: /"is-IS"/],
			[find: /"ita-CHE"/, replacement: /"it-CH"/],
			[find: /"ita-ITA"/, replacement: /"it-IT"/],
			[find: /"ita-SVN"/, replacement: /"it-SI"/],
			[find: /"jpn-JPN"/, replacement: /"ja-JP"/],
			[find: /"kaa-UZB"/, replacement: /"kaa-UZ"/],
			[find: /"kan-IND"/, replacement: /"kn-IN"/],
			[find: /"kau-NER"/, replacement: /"kr-NE"/],
			[find: /"kaz-KAZ"/, replacement: /"kk-KZ"/],
			[find: /"kaz-MNG"/, replacement: /"kk-MN"/],
			[find: /"khm-KHM"/, replacement: /"km-KH"/],
			[find: /"kin-RWA"/, replacement: /"rw-RW"/],
			[find: /"kir-KGZ"/, replacement: /"ky-KG"/],
			[find: /"kon-COD"/, replacement: /"kg-CD"/],
			[find: /"kor-KOR"/, replacement: /"ko-KR"/],
			[find: /"kur-IRN"/, replacement: /"ku-IR"/],
			[find: /"kur-IRQ"/, replacement: /"ku-IQ"/],
			[find: /"kur-TUR"/, replacement: /"ku-TR"/],
			[find: /"lao-LAO"/, replacement: /"lo-LA"/],
			[find: /"lav-LVA"/, replacement: /"lv-LV"/],
			[find: /"ldd-ITA"/, replacement: /"lad-IT"/],
			[find: /"lgg-UGA"/, replacement: /"lg-UG"/],
			[find: /"lin-COD"/, replacement: /"ln-CD"/],
			[find: /"lit-LTU"/, replacement: /"lt-LT"/],
			[find: /"ltz-LUX"/, replacement: /"lb-LU"/],
			[find: /"lua-COD"/, replacement: /"lua-CD"/],
			[find: /"lug-UGA"/, replacement: /"lgg-UG"/],
			[find: /"luo-UGA"/, replacement: /"luo-UG"/],
			[find: /"mao-NZL"/, replacement: /"mi-NZ"/],
			[find: /"mar-IND"/, replacement: /"mr-IN"/],
			[find: /"miq-HND"/, replacement: /"miq-HN"/],
			[find: /"mkd-MKD"/, replacement: /"mk-MK"/],
			[find: /"mlt-MLT"/, replacement: /"mt-MT"/],
			[find: /"mne-MNE"/, replacement: /"sr-ME"/],
			[find: /"mon-MNG"/, replacement: /"mn-MN"/],
			[find: /"mos-BFA"/, replacement: /"mos-BF"/],
			[find: /"msa-BRN"/, replacement: /"ms-BN"/],
			[find: /"msa-MYS"/, replacement: /"ms-MY"/],
			[find: /"msa-SGP"/, replacement: /"ms-SG"/],
			[find: /"ndc-MOZ"/, replacement: /"ndc-MZ"/],
			[find: /"nep-NPL"/, replacement: /"ne-NP"/],
			[find: /"ngl-MOZ"/, replacement: /"ngl-MZ"/],
			[find: /"ngp-MOZ"/, replacement: /"ngp-MZ"/],
			[find: /"nld-BEL"/, replacement: /"nl-BE"/],
			[find: /"nld-NLD"/, replacement: /"nl-NL"/],
			[find: /"nno-NOR"/, replacement: /"nn-NO"/],
			[find: /"nob-NOR"/, replacement: /"nb-NO"/],
			[find: /"nso-ZAF"/, replacement: /"nso-ZA"/],
			[find: /"nyn-UGA"/, replacement: /"nyn-UG"/],
			[find: /"nyo-UGA"/, replacement: /"nyo-UG"/],
			[find: /"ori-IND"/, replacement: /"or-IN"/],
			[find: /"orm-ETH"/, replacement: /"om-ET"/],
			[find: /"pan-ZZZ"/, replacement: /"pa-ZZ"/],
			[find: /"pga-SSD"/, replacement: /"pga-SS"/],
			[find: /"pol-LTU"/, replacement: /"pl-LT"/],
			[find: /"pol-NOR"/, replacement: /"pl-NO"/],
			[find: /"pol-POL"/, replacement: /"pl-PL"/],
			[find: /"por-AGO"/, replacement: /"pt-AO"/],
			[find: /"por-BRA"/, replacement: /"pt-BR"/],
			[find: /"por-MAC"/, replacement: /"pt-MO"/],
			[find: /"por-MOZ"/, replacement: /"pt-MZ"/],
			[find: /"por-PRT"/, replacement: /"pt-PT"/],
			[find: /"por-TLS"/, replacement: /"pt-TL"/],
			[find: /"pus-AFG"/, replacement: /"ps-AF"/],
			[find: /"pus-PAK"/, replacement: /"ps-PK"/],
			[find: /"qes-EST"/, replacement: /"et-EQ"/],
			[find: /"qhe-ISR"/, replacement: /"he-IQ"/],
			[find: /"qsk-SVK"/, replacement: /"skq-SK"/],
			[find: /"qsl-SVN"/, replacement: /"sl-SQ"/],
			[find: /"que-PER"/, replacement: /"qu-PE"/],
			[find: /"rom-HUN"/, replacement: /"rom-HU"/],
			[find: /"ron-MDA"/, replacement: /"ro-MD"/],
			[find: /"ron-ROU"/, replacement: /"ro-RO"/],
			[find: /"ron-ZZZ"/, replacement: /"ro-ZZ"/],
			[find: /"rus-AZE"/, replacement: /"ru-AZ"/],
			[find: /"rus-BLR"/, replacement: /"ru-BY"/],
			[find: /"rus-EST"/, replacement: /"ru-EE"/],
			[find: /"rus-GEO"/, replacement: /"ru-GE"/],
			[find: /"rus-ISR"/, replacement: /"ru-IL"/],
			[find: /"rus-KAZ"/, replacement: /"ru-KZ"/],
			[find: /"rus-KGZ"/, replacement: /"ru-KG"/],
			[find: /"rus-LTU"/, replacement: /"ru-LT"/],
			[find: /"rus-LVA"/, replacement: /"ru-LV"/],
			[find: /"rus-MDA"/, replacement: /"ru-MD"/],
			[find: /"rus-QAZ"/, replacement: /"ru-QZ"/],
			[find: /"rus-RUS"/, replacement: /"ru-RU"/],
			[find: /"rus-UKR"/, replacement: /"ru-UA"/],
			[find: /"rus-UZB"/, replacement: /"ru-UZ"/],
			[find: /"sag-CAF"/, replacement: /"sg-CF"/],
			[find: /"seh-MOZ"/, replacement: /"seh-MZ"/],
			[find: /"sin-LKA"/, replacement: /"si-LK"/],
			[find: /"slo-SVK"/, replacement: /"sk-SK"/],
			[find: /"slv-AUT"/, replacement: /"sl-AT"/],
			[find: /"slv-ITA"/, replacement: /"sl-IT"/],
			[find: /"slv-SVN"/, replacement: /"sl-SI"/],
			[find: /"smo-ZZZ"/, replacement: /"sm-ZZ"/],
			[find: /"sna-MOZ"/, replacement: /"sn-MZ"/],
			[find: /"snd-PAK"/, replacement: /"sd-PK"/],
			[find: /"som-SOM"/, replacement: /"so-SO"/],
			[find: /"som-ZZZ"/, replacement: /"so-ZZ"/],
			[find: /"sot-ZAF"/, replacement: /"st-ZA"/],
			[find: /"sqi-ALB"/, replacement: /"sq-AL"/],
			[find: /"sqi-KSV"/, replacement: /"sq-XK"/],
			[find: /"sqi-MKD"/, replacement: /"sq-MK"/],
			[find: /"sqi-MNE"/, replacement: /"sq-ME"/],
			[find: /"sqi-ZZZ"/, replacement: /"sq-ZZ"/],
			[find: /"srp-AUT"/, replacement: /"sh-AT"/],
			[find: /"srp-BIH"/, replacement: /"sr-BA"/],
			[find: /"srp-HRV"/, replacement: /"sr-HR"/],
			[find: /"srp-KSV"/, replacement: /"sr-XK"/],
			[find: /"srp-SRB"/, replacement: /"sr-RS"/],
			[find: /"swa-COD"/, replacement: /"sw-CD"/],
			[find: /"swa-KEN"/, replacement: /"sw-KE"/],
			[find: /"swe-FIN"/, replacement: /"sv-FI"/],
			[find: /"swe-SWE"/, replacement: /"sv-SE"/],
			[find: /"tam-IND"/, replacement: /"ta-IN"/],
			[find: /"tam-LKA"/, replacement: /"ta-LK"/],
			[find: /"tam-MYS"/, replacement: /"ta-MY"/],
			[find: /"tam-SGP"/, replacement: /"ta-SG"/],
			[find: /"tat-ZZZ"/, replacement: /"tt-ZZ"/],
			[find: /"tel-IND"/, replacement: /"te-IN"/],
			[find: /"teo-UGA"/, replacement: /"teo-UG"/],
			[find: /"tet-TLS"/, replacement: /"tet-TL"/],
			[find: /"tgl-PHL"/, replacement: /"tl-PH"/],
			[find: /"tha-THA"/, replacement: /"th-TH"/],
			[find: /"tir-ERI"/, replacement: /"ti-ER"/],
			[find: /"tir-ETH"/, replacement: /"ti-ET"/],
			[find: /"tsn-ZAF"/, replacement: /"tn-ZA"/],
			[find: /"tso-MOZ"/, replacement: /"ts-MZ"/],
			[find: /"ttq-NER"/, replacement: /"ttq-NE"/],
			[find: /"tur-AUT"/, replacement: /"tr-AT"/],
			[find: /"tur-TUR"/, replacement: /"tr-TR"/],
			[find: /"tur-ZZZ"/, replacement: /"tr-ZZ"/],
			[find: /"ukr-UKR"/, replacement: /"uk-UA"/],
			[find: /"ukr-ZZZ"/, replacement: /"uk-ZZ"/],
			[find: /"urd-PAK"/, replacement: /"ur-PK"/],
			[find: /"urd-ZZZ"/, replacement: /"ur-ZZ"/],
			[find: /"uzb-KGZ"/, replacement: /"uz-KG"/],
			[find: /"uzb-UZB"/, replacement: /"uz-UZ"/],
			[find: /"val-ESP"/, replacement: /"ca-VL"/],
			[find: /"vie-VNM"/, replacement: /"vi-VN"/],
			[find: /"vie-ZZZ"/, replacement: /"vi-ZZ"/],
			[find: /"vmw-MOZ"/, replacement: /"vmw-MZ"/],
			[find: /"wol-SEN"/, replacement: /"wo-SN"/],
			[find: /"xho-ZAF"/, replacement: /"xh-ZA"/],
			[find: /"yid-ZZZ"/, replacement: /"yi-ZZ"/],
			[find: /"yor-NGA"/, replacement: /"yo-NG"/],
			[find: /"zed-ZDL"/, replacement: /"zd-ZD"/],
			[find: /"zho-CHN"/, replacement: /"zh-CN"/],
			[find: /"zho-CNS"/, replacement: /"zh-SH"/],
			[find: /"zho-HKG"/, replacement: /"zh-HK"/],
			[find: /"zho-MAC"/, replacement: /"zh-MO"/],
			[find: /"zho-MYS"/, replacement: /"zh-MY"/],
			[find: /"zho-SGP"/, replacement: /"zh-SG"/],
			[find: /"zho-TAP"/, replacement: /"zh-TW"/],
			[find: /"zho-ZZZ"/, replacement: /"zh-ZZ"/],
			[find: /"zhs-ZZZ"/, replacement: /"zh-ZS"/],
			[find: /"zul-ZAF"/, replacement: /"zu-ZA"/],
		]
		break
	case COMPILE:
		dir = project.projectProperties.targetRoot
		// restores ETS language codes
		replacePair = [
			[find: /"af-ZA"/, replacement: /"afr-ZAF"/],
			[find: /"ak-GH"/, replacement: /"aka-GHA"/],
			[find: /"am-ET"/, replacement: /"amh-ETH"/],
			[find: /"am-ZZ"/, replacement: /"amh-ZZZ"/],
			[find: /"ar-AE"/, replacement: /"ara-ARE"/],
			[find: /"ar-BH"/, replacement: /"ara-BHR"/],
			[find: /"ar-DJ"/, replacement: /"ara-DJI"/],
			[find: /"ar-DU"/, replacement: /"ara-UAE"/],
			[find: /"ar-DZ"/, replacement: /"ara-DZA"/],
			[find: /"ar-EG"/, replacement: /"ara-EGY"/],
			[find: /"ar-IL"/, replacement: /"ara-ISR"/],
			[find: /"ar-IQ"/, replacement: /"ara-IRQ"/],
			[find: /"ar-JO"/, replacement: /"ara-JOR"/],
			[find: /"ar-KW"/, replacement: /"ara-KWT"/],
			[find: /"ar-LY"/, replacement: /"ara-LBY"/],
			[find: /"ar-MA"/, replacement: /"ara-MAR"/],
			[find: /"ar-OM"/, replacement: /"ara-OMN"/],
			[find: /"ar-PS"/, replacement: /"ara-PSE"/],
			[find: /"ar-QA"/, replacement: /"ara-QAT"/],
			[find: /"ar-SA"/, replacement: /"ara-SAU"/],
			[find: /"ar-SY"/, replacement: /"ara-SYR"/],
			[find: /"ar-TN"/, replacement: /"ara-TUN"/],
			[find: /"ar-YE"/, replacement: /"ara-YEM"/],
			[find: /"ar-ZZ"/, replacement: /"ara-ZZZ"/],
			[find: /"az-GE"/, replacement: /"azj-GEO"/],
			[find: /"az-QZ"/, replacement: /"aze-QAZ"/],
			[find: /"be-BY"/, replacement: /"bel-BLR"/],
			[find: /"be-ZZ"/, replacement: /"bel-ZZZ"/],
			[find: /"bg-BG"/, replacement: /"bul-BGR"/],
			[find: /"bik-PH"/, replacement: /"bik-PHL"/],
			[find: /"bm-ML"/, replacement: /"bam-MLI"/],
			[find: /"bn-BD"/, replacement: /"ben-BGD"/],
			[find: /"bn-IN"/, replacement: /"ben-IND"/],
			[find: /"bs-BA"/, replacement: /"bos-BIH"/],
			[find: /"bs-RS"/, replacement: /"bos-SRB"/],
			[find: /"ca-ES"/, replacement: /"cat-ESP"/],
			[find: /"ca-VL"/, replacement: /"val-ESP"/],
			[find: /"cab-HN"/, replacement: /"cab-HND"/],
			[find: /"ceb-PH"/, replacement: /"ceb-PHL"/],
			[find: /"cs-CZ"/, replacement: /"ces-CZE"/],
			[find: /"cy-GB"/, replacement: /"cym-QUK"/],
			[find: /"da-DK"/, replacement: /"dan-DNK"/],
			[find: /"dag-GH"/, replacement: /"dag-GHA"/],
			[find: /"de-AT"/, replacement: /"deu-AUT"/],
			[find: /"de-BE"/, replacement: /"deu-BEL"/],
			[find: /"de-CH"/, replacement: /"deu-CHE"/],
			[find: /"de-DE"/, replacement: /"deu-DEU"/],
			[find: /"de-IT"/, replacement: /"deu-ITA"/],
			[find: /"de-LI"/, replacement: /"deu-LIE"/],
			[find: /"de-LU"/, replacement: /"deu-LUX"/],
			[find: /"de-ZZ"/, replacement: /"deu-ZZZ"/],
			[find: /"dje-NE"/, replacement: /"dje-NER"/],
			[find: /"dyu-BF"/, replacement: /"dyu-BFA"/],
			[find: /"dz-BT"/, replacement: /"dzo-BTN"/],
			[find: /"ee-GH"/, replacement: /"ewe-GHA"/],
			[find: /"el-AL"/, replacement: /"ell-ALB"/],
			[find: /"el-CY"/, replacement: /"ell-QCY"/],
			[find: /"el-GR"/, replacement: /"ell-GRC"/],
			[find: /"en-AB"/, replacement: /"eng-QSC"/],
			[find: /"en-AE"/, replacement: /"eng-ARE"/],
			[find: /"en-AT"/, replacement: /"eng-AUT"/],
			[find: /"en-AU"/, replacement: /"eng-AUS"/],
			[find: /"en-BH"/, replacement: /"eng-BHR"/],
			[find: /"en-BN"/, replacement: /"eng-BRN"/],
			[find: /"en-BT"/, replacement: /"eng-BTN"/],
			[find: /"en-BU"/, replacement: /"eng-NIR"/],
			[find: /"en-BW"/, replacement: /"eng-BWA"/],
			[find: /"en-CA"/, replacement: /"eng-CAN"/],
			[find: /"en-CY"/, replacement: /"eng-QCY"/],
			[find: /"en-EG"/, replacement: /"eng-EGY"/],
			[find: /"en-EN"/, replacement: /"eng-ENG"/],
			[find: /"en-ES"/, replacement: /"eng-ESP"/],
			[find: /"en-GB"/, replacement: /"eng-GBR"/],
			[find: /"en-GH"/, replacement: /"eng-GHA"/],
			[find: /"en-HK"/, replacement: /"eng-HKG"/],
			[find: /"en-IE"/, replacement: /"eng-IRL"/],
			[find: /"en-IN"/, replacement: /"eng-QIN"/],
			[find: /"en-JM"/, replacement: /"eng-JAM"/],
			[find: /"en-KE"/, replacement: /"eng-KEN"/],
			[find: /"en-KW"/, replacement: /"eng-KWT"/],
			[find: /"en-LB"/, replacement: /"eng-LBN"/],
			[find: /"en-LU"/, replacement: /"eng-LUX"/],
			[find: /"en-MO"/, replacement: /"eng-MAC"/],
			[find: /"en-MT"/, replacement: /"eng-MLT"/],
			[find: /"en-MU"/, replacement: /"eng-MUS"/],
			[find: /"en-MY"/, replacement: /"eng-MYS"/],
			[find: /"en-NG"/, replacement: /"eng-NGA"/],
			[find: /"en-NO"/, replacement: /"eng-NOR"/],
			[find: /"en-NZ"/, replacement: /"eng-NZL"/],
			[find: /"en-OM"/, replacement: /"eng-OMN"/],
			[find: /"en-PA"/, replacement: /"eng-PAN"/],
			[find: /"en-PH"/, replacement: /"eng-PHL"/],
			[find: /"en-QA"/, replacement: /"eng-QAT"/],
			[find: /"en-SA"/, replacement: /"eng-SAU"/],
			[find: /"en-SE"/, replacement: /"eng-SWE"/],
			[find: /"en-SG"/, replacement: /"eng-SGP"/],
			[find: /"en-SU"/, replacement: /"eng-QUK"/],
			[find: /"en-TT"/, replacement: /"eng-TTO"/],
			[find: /"en-TW"/, replacement: /"eng-TAP"/],
			[find: /"en-US"/, replacement: /"eng-USA"/],
			[find: /"en-ZA"/, replacement: /"eng-ZAF"/],
			[find: /"en-ZZ"/, replacement: /"eng-ZZZ"/],
			[find: /"es-AR"/, replacement: /"esp-ARG"/],
			[find: /"es-BO"/, replacement: /"esp-BOL"/],
			[find: /"es-CL"/, replacement: /"esp-CHL"/],
			[find: /"es-CO"/, replacement: /"esp-COL"/],
			[find: /"es-CR"/, replacement: /"esp-CRI"/],
			[find: /"es-DO"/, replacement: /"esp-DOM"/],
			[find: /"es-EC"/, replacement: /"esp-ECU"/],
			[find: /"es-ES"/, replacement: /"esp-ESP"/],
			[find: /"es-GT"/, replacement: /"esp-GTM"/],
			[find: /"es-HN"/, replacement: /"esp-HND"/],
			[find: /"es-MX"/, replacement: /"esp-MEX"/],
			[find: /"es-NI"/, replacement: /"esp-NIC"/],
			[find: /"es-PA"/, replacement: /"esp-PAN"/],
			[find: /"es-PE"/, replacement: /"esp-PER"/],
			[find: /"es-PR"/, replacement: /"esp-PRI"/],
			[find: /"es-PY"/, replacement: /"esp-PRY"/],
			[find: /"es-SV"/, replacement: /"esp-SLV"/],
			[find: /"es-US"/, replacement: /"esp-USA"/],
			[find: /"es-UY"/, replacement: /"esp-URY"/],
			[find: /"es-VE"/, replacement: /"esp-VEN"/],
			[find: /"es-ZZ"/, replacement: /"esp-ZZZ"/],
			[find: /"et-EE"/, replacement: /"est-EST"/],
			[find: /"et-EQ"/, replacement: /"qes-EST"/],
			[find: /"eu-ES"/, replacement: /"eus-ESP"/],
			[find: /"fa-AF"/, replacement: /"fas-AFG"/],
			[find: /"fa-IR"/, replacement: /"fas-IRN"/],
			[find: /"fa-ZZ"/, replacement: /"fas-ZZZ"/],
			[find: /"fi-FI"/, replacement: /"fin-FIN"/],
			[find: /"fo-DK"/, replacement: /"fao-DNK"/],
			[find: /"fr-BE"/, replacement: /"fra-BEL"/],
			[find: /"fr-BF"/, replacement: /"fra-BFA"/],
			[find: /"fr-CA"/, replacement: /"fra-CAN"/],
			[find: /"fr-CD"/, replacement: /"fra-COD"/],
			[find: /"fr-CH"/, replacement: /"fra-CHE"/],
			[find: /"fr-FR"/, replacement: /"fra-FRA"/],
			[find: /"fr-LB"/, replacement: /"fra-LBN"/],
			[find: /"fr-LU"/, replacement: /"fra-LUX"/],
			[find: /"fr-MA"/, replacement: /"fra-MAR"/],
			[find: /"fr-NE"/, replacement: /"fra-NER"/],
			[find: /"fr-SN"/, replacement: /"fra-SEN"/],
			[find: /"fr-ZZ"/, replacement: /"fra-ZZZ"/],
			[find: /"fuh-BF"/, replacement: /"ful-BFA"/],
			[find: /"fuq-NE"/, replacement: /"ful-NER"/],
			[find: /"ga-IE"/, replacement: /"gle-IRL"/],
			[find: /"gaa-GH"/, replacement: /"gaa-GHA"/],
			[find: /"gl-ES"/, replacement: /"glg-ESP"/],
			[find: /"gn-PY"/, replacement: /"grn-PRY"/],
			[find: /"gu-IN"/, replacement: /"guj-IND"/],
			[find: /"ha-GH"/, replacement: /"hau-GHA"/],
			[find: /"ha-NE"/, replacement: /"hau-NER"/],
			[find: /"ha-NG"/, replacement: /"hau-NGA"/],
			[find: /"he-IL"/, replacement: /"heb-ISR"/],
			[find: /"he-IQ"/, replacement: /"qhe-ISR"/],
			[find: /"hi-IN"/, replacement: /"hin-QIN"/],
			[find: /"hil-PH"/, replacement: /"hil-PHL"/],
			[find: /"hr-BA"/, replacement: /"hrv-BIH"/],
			[find: /"hr-HR"/, replacement: /"hrv-HRV"/],
			[find: /"ht-HT"/, replacement: /"hat-HAT"/],
			[find: /"hu-HU"/, replacement: /"hun-HUN"/],
			[find: /"hu-RO"/, replacement: /"hun-ROU"/],
			[find: /"hu-RS"/, replacement: /"hun-SRB"/],
			[find: /"hu-SI"/, replacement: /"hun-SVN"/],
			[find: /"hu-SK"/, replacement: /"hun-SVK"/],
			[find: /"hy-AM"/, replacement: /"hye-ARM"/],
			[find: /"id-ID"/, replacement: /"ind-IDN"/],
			[find: /"id-TL"/, replacement: /"ind-TLS"/],
			[find: /"ig-NG"/, replacement: /"ibo-NGA"/],
			[find: /"is-IS"/, replacement: /"isl-ISL"/],
			[find: /"it-CH"/, replacement: /"ita-CHE"/],
			[find: /"it-IT"/, replacement: /"ita-ITA"/],
			[find: /"it-SI"/, replacement: /"ita-SVN"/],
			[find: /"ja-JP"/, replacement: /"jpn-JPN"/],
			[find: /"ka-GE"/, replacement: /"geo-GEO"/],
			[find: /"kaa-UZ"/, replacement: /"kaa-UZB"/],
			[find: /"kg-CD"/, replacement: /"kon-COD"/],
			[find: /"kk-KZ"/, replacement: /"kaz-KAZ"/],
			[find: /"kk-MN"/, replacement: /"kaz-MNG"/],
			[find: /"km-KH"/, replacement: /"khm-KHM"/],
			[find: /"kn-IN"/, replacement: /"kan-IND"/],
			[find: /"ko-KR"/, replacement: /"kor-KOR"/],
			[find: /"kr-NE"/, replacement: /"kau-NER"/],
			[find: /"ku-IQ"/, replacement: /"kur-IRQ"/],
			[find: /"ku-IR"/, replacement: /"kur-IRN"/],
			[find: /"ku-TR"/, replacement: /"kur-TUR"/],
			[find: /"ky-KG"/, replacement: /"kir-KGZ"/],
			[find: /"lad-IT"/, replacement: /"ldd-ITA"/],
			[find: /"lb-LU"/, replacement: /"ltz-LUX"/],
			[find: /"lg-UG"/, replacement: /"lgg-UGA"/],
			[find: /"lgg-UG"/, replacement: /"lug-UGA"/],
			[find: /"ln-CD"/, replacement: /"lin-COD"/],
			[find: /"lo-LA"/, replacement: /"lao-LAO"/],
			[find: /"lt-LT"/, replacement: /"lit-LTU"/],
			[find: /"lua-CD"/, replacement: /"lua-COD"/],
			[find: /"luo-UG"/, replacement: /"luo-UGA"/],
			[find: /"lv-LV"/, replacement: /"lav-LVA"/],
			[find: /"mi-NZ"/, replacement: /"mao-NZL"/],
			[find: /"miq-HN"/, replacement: /"miq-HND"/],
			[find: /"mk-MK"/, replacement: /"mkd-MKD"/],
			[find: /"mn-MN"/, replacement: /"mon-MNG"/],
			[find: /"mos-BF"/, replacement: /"mos-BFA"/],
			[find: /"mr-IN"/, replacement: /"mar-IND"/],
			[find: /"ms-BN"/, replacement: /"msa-BRN"/],
			[find: /"ms-MY"/, replacement: /"msa-MYS"/],
			[find: /"ms-SG"/, replacement: /"msa-SGP"/],
			[find: /"mt-MT"/, replacement: /"mlt-MLT"/],
			[find: /"nb-NO"/, replacement: /"nob-NOR"/],
			[find: /"ndc-MZ"/, replacement: /"ndc-MOZ"/],
			[find: /"ne-NP"/, replacement: /"nep-NPL"/],
			[find: /"ngl-MZ"/, replacement: /"ngl-MOZ"/],
			[find: /"ngp-MZ"/, replacement: /"ngp-MOZ"/],
			[find: /"nl-BE"/, replacement: /"nld-BEL"/],
			[find: /"nl-NL"/, replacement: /"nld-NLD"/],
			[find: /"nn-NO"/, replacement: /"nno-NOR"/],
			[find: /"nso-ZA"/, replacement: /"nso-ZAF"/],
			[find: /"nyn-UG"/, replacement: /"nyn-UGA"/],
			[find: /"nyo-UG"/, replacement: /"nyo-UGA"/],
			[find: /"om-ET"/, replacement: /"orm-ETH"/],
			[find: /"or-IN"/, replacement: /"ori-IND"/],
			[find: /"pa-ZZ"/, replacement: /"pan-ZZZ"/],
			[find: /"pga-SS"/, replacement: /"pga-SSD"/],
			[find: /"pl-LT"/, replacement: /"pol-LTU"/],
			[find: /"pl-NO"/, replacement: /"pol-NOR"/],
			[find: /"pl-PL"/, replacement: /"pol-POL"/],
			[find: /"ps-AF"/, replacement: /"pus-AFG"/],
			[find: /"ps-PK"/, replacement: /"pus-PAK"/],
			[find: /"pt-AO"/, replacement: /"por-AGO"/],
			[find: /"pt-BR"/, replacement: /"por-BRA"/],
			[find: /"pt-MO"/, replacement: /"por-MAC"/],
			[find: /"pt-MZ"/, replacement: /"por-MOZ"/],
			[find: /"pt-PT"/, replacement: /"por-PRT"/],
			[find: /"pt-TL"/, replacement: /"por-TLS"/],
			[find: /"qu-PE"/, replacement: /"que-PER"/],
			[find: /"ro-MD"/, replacement: /"ron-MDA"/],
			[find: /"ro-RO"/, replacement: /"ron-ROU"/],
			[find: /"ro-ZZ"/, replacement: /"ron-ZZZ"/],
			[find: /"rom-HU"/, replacement: /"rom-HUN"/],
			[find: /"ru-AZ"/, replacement: /"rus-AZE"/],
			[find: /"ru-BY"/, replacement: /"rus-BLR"/],
			[find: /"ru-EE"/, replacement: /"rus-EST"/],
			[find: /"ru-GE"/, replacement: /"rus-GEO"/],
			[find: /"ru-IL"/, replacement: /"rus-ISR"/],
			[find: /"ru-KG"/, replacement: /"rus-KGZ"/],
			[find: /"ru-KZ"/, replacement: /"rus-KAZ"/],
			[find: /"ru-LT"/, replacement: /"rus-LTU"/],
			[find: /"ru-LV"/, replacement: /"rus-LVA"/],
			[find: /"ru-MD"/, replacement: /"rus-MDA"/],
			[find: /"ru-QZ"/, replacement: /"rus-QAZ"/],
			[find: /"ru-RU"/, replacement: /"rus-RUS"/],
			[find: /"ru-UA"/, replacement: /"rus-UKR"/],
			[find: /"ru-UZ"/, replacement: /"rus-UZB"/],
			[find: /"rw-RW"/, replacement: /"kin-RWA"/],
			[find: /"sd-PK"/, replacement: /"snd-PAK"/],
			[find: /"seh-MZ"/, replacement: /"seh-MOZ"/],
			[find: /"sg-CF"/, replacement: /"sag-CAF"/],
			[find: /"sh-AT"/, replacement: /"srp-AUT"/],
			[find: /"si-LK"/, replacement: /"sin-LKA"/],
			[find: /"sk-SK"/, replacement: /"slo-SVK"/],
			[find: /"skq-SK"/, replacement: /"qsk-SVK"/],
			[find: /"sl-AT"/, replacement: /"slv-AUT"/],
			[find: /"sl-IT"/, replacement: /"slv-ITA"/],
			[find: /"sl-SI"/, replacement: /"slv-SVN"/],
			[find: /"sl-SQ"/, replacement: /"qsl-SVN"/],
			[find: /"sm-ZZ"/, replacement: /"smo-ZZZ"/],
			[find: /"sn-MZ"/, replacement: /"sna-MOZ"/],
			[find: /"so-SO"/, replacement: /"som-SOM"/],
			[find: /"so-ZZ"/, replacement: /"som-ZZZ"/],
			[find: /"sq-AL"/, replacement: /"sqi-ALB"/],
			[find: /"sq-ME"/, replacement: /"sqi-MNE"/],
			[find: /"sq-MK"/, replacement: /"sqi-MKD"/],
			[find: /"sq-XK"/, replacement: /"sqi-KSV"/],
			[find: /"sq-ZZ"/, replacement: /"sqi-ZZZ"/],
			[find: /"sr-BA"/, replacement: /"srp-BIH"/],
			[find: /"sr-HR"/, replacement: /"srp-HRV"/],
			[find: /"sr-ME"/, replacement: /"mne-MNE"/],
			[find: /"sr-RS"/, replacement: /"srp-SRB"/],
			[find: /"sr-XK"/, replacement: /"srp-KSV"/],
			[find: /"st-ZA"/, replacement: /"sot-ZAF"/],
			[find: /"sv-FI"/, replacement: /"swe-FIN"/],
			[find: /"sv-SE"/, replacement: /"swe-SWE"/],
			[find: /"sw-CD"/, replacement: /"swa-COD"/],
			[find: /"sw-KE"/, replacement: /"swa-KEN"/],
			[find: /"ta-IN"/, replacement: /"tam-IND"/],
			[find: /"ta-LK"/, replacement: /"tam-LKA"/],
			[find: /"ta-MY"/, replacement: /"tam-MYS"/],
			[find: /"ta-SG"/, replacement: /"tam-SGP"/],
			[find: /"te-IN"/, replacement: /"tel-IND"/],
			[find: /"teo-UG"/, replacement: /"teo-UGA"/],
			[find: /"tet-TL"/, replacement: /"tet-TLS"/],
			[find: /"th-TH"/, replacement: /"tha-THA"/],
			[find: /"ti-ER"/, replacement: /"tir-ERI"/],
			[find: /"ti-ET"/, replacement: /"tir-ETH"/],
			[find: /"tl-PH"/, replacement: /"tgl-PHL"/],
			[find: /"tn-ZA"/, replacement: /"tsn-ZAF"/],
			[find: /"tr-AT"/, replacement: /"tur-AUT"/],
			[find: /"tr-TR"/, replacement: /"tur-TUR"/],
			[find: /"tr-ZZ"/, replacement: /"tur-ZZZ"/],
			[find: /"ts-MZ"/, replacement: /"tso-MOZ"/],
			[find: /"tt-ZZ"/, replacement: /"tat-ZZZ"/],
			[find: /"ttq-NE"/, replacement: /"ttq-NER"/],
			[find: /"uk-UA"/, replacement: /"ukr-UKR"/],
			[find: /"uk-ZZ"/, replacement: /"ukr-ZZZ"/],
			[find: /"ur-PK"/, replacement: /"urd-PAK"/],
			[find: /"ur-ZZ"/, replacement: /"urd-ZZZ"/],
			[find: /"uz-KG"/, replacement: /"uzb-KGZ"/],
			[find: /"uz-UZ"/, replacement: /"uzb-UZB"/],
			[find: /"vi-VN"/, replacement: /"vie-VNM"/],
			[find: /"vi-ZZ"/, replacement: /"vie-ZZZ"/],
			[find: /"vmw-MZ"/, replacement: /"vmw-MOZ"/],
			[find: /"wo-SN"/, replacement: /"wol-SEN"/],
			[find: /"xh-ZA"/, replacement: /"xho-ZAF"/],
			[find: /"yi-ZZ"/, replacement: /"yid-ZZZ"/],
			[find: /"yo-NG"/, replacement: /"yor-NGA"/],
			[find: /"zd-ZD"/, replacement: /"zed-ZDL"/],
			[find: /"zh-CN"/, replacement: /"zho-CHN"/],
			[find: /"zh-HK"/, replacement: /"zho-HKG"/],
			[find: /"zh-MO"/, replacement: /"zho-MAC"/],
			[find: /"zh-MY"/, replacement: /"zho-MYS"/],
			[find: /"zh-SG"/, replacement: /"zho-SGP"/],
			[find: /"zh-SH"/, replacement: /"zho-CNS"/],
			[find: /"zh-TW"/, replacement: /"zho-TAP"/],
			[find: /"zh-ZS"/, replacement: /"zhs-ZZZ"/],
			[find: /"zh-ZZ"/, replacement: /"zho-ZZZ"/],
			[find: /"zu-ZA"/, replacement: /"zul-ZAF"/],
        ]
        break
    default:
        return null // No output
}

String ENCODING = 'UTF-8'
File rootDir = new File(dir)
int modifiedFiles = 0

// options as map
def options = [
    type       : groovy.io.FileType.FILES,
    nameFilter : ~/.*\.xlf/
]

// replacer as closure
def replacer = {file ->
    String text = file.getText ENCODING
    String replaced = text
    replacePair.each {replaced = replaced.replaceAll it.find, it.replacement}
    if (text != replaced) {
        file.setText replaced, ENCODING
        console.println "modified: $file"
        modifiedFiles++
    }
}

def reloadProjectOnetime = {
    LOAD.skipTraverse = true    // avoid potentially infinity reloading loop
    javax.swing.SwingUtilities.invokeLater({
        org.omegat.gui.main.ProjectUICommands.projectReload()
    } as Runnable)
}

// do replace
rootDir.traverse options, replacer

/*if (modifiedFiles > 0 && eventType == LOAD) {
    console.println "$modifiedFiles file(s) modified."
    reloadProjectOnetime()
}*/
